default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/psf/black
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/PyCQA/isort
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    hooks:
    -   id: flake8

-   repo: https://github.com/python/mypy
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --follow-imports=silent, --strict-optional, --warn-no-return]

-   repo: https://github.com/PyCQA/bandit
    hooks:
    -   id: bandit
    
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-added-large-files
        args: [--maxkb=50000]

      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
