default_language_version:
    python: python3.10

repos:
  -
    repo: https://github.com/PyCQA/isort
    rev: v5.9.3
    hooks:
      -
        id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        exclude: ^\.
    repo: https://github.com/psf/black
    rev: v217b0
    hooks:
      -
        id: black
        name: black
        entry: black
        language: system
        types: [python]
        exclude: ^\.
    repo: https://github.com/pycqa/flake8
    rev: v3.9.2
    hooks:
      -
        id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        exclude: ^\.
    repo: https://github.com/python/mypy
    rev: v1.1.1
    hooks:
      -
        id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: ^\.
    repo: https://github.com/PyCQA/bandit
    rev: v1.7.5
    hooks:
      -
        id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        exclude: ^\.
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-added-large-files
        args: [--maxkb=50000]

      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
